# Generated by Django 5.2.17 on 2026-10-01 01:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auth_user_email_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente_publicacao', 'Pendente de publicação'), ('pendente', 'Pendente (aguardando o worker)'), ('processado', 'Processado'), ('falha', 'Falha')], db_index=True, default='pendente_publicacao', max_length=32, verbose_name='status')),
                ('itens', models.JSONField(default=list, verbose_name='itens')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='chave de idempotência')),
                ('simular_falha', models.BooleanField(default=False, verbose_name='simular falha')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='tentativas')),
                ('processado_em', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('motivo_falha', models.CharField(blank=True, default='', max_length=200, verbose_name='motivo da falha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', '-created_at'], name='core_pedido_usuario_created_i')],
            },
        ),
    ]
