# Generated by Django 5.2.17 on 2026-10-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('cartao_credito', 'Cartão de crédito'), ('pix', 'PIX'), ('boleto', 'Boleto')], max_length=32, verbose_name='método')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('transacao_id', models.CharField(max_length=64, unique=True, verbose_name='id da transação')),
                ('aprovado', models.BooleanField(default=False, verbose_name='aprovado')),
                ('motivo_recusa', models.CharField(blank=True, default='', max_length=200, verbose_name='motivo da recusa')),
                ('status', models.CharField(choices=[('registrado', 'Registrado (aguardando publicação do evento)'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado')], db_index=True, default='registrado', max_length=32, verbose_name='status')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='chave de idempotência')),
                ('simular_falha', models.BooleanField(default=False, verbose_name='simular falha')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='tentativas')),
                ('notificado_em', models.DateTimeField(blank=True, null=True, verbose_name='notificado em')),
                ('motivo_falha', models.CharField(blank=True, default='', max_length=200, verbose_name='motivo da falha')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='core.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS'), ('push', 'Push')], default='email', max_length=16, verbose_name='canal')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('enviada_em', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificacoes', to='core.pedido', verbose_name='pedido')),
                ('pagamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='notificacao', to='core.pagamento', verbose_name='pagamento')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-enviada_em'],
            },
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['-created_at'], name='core_pagamento_created_desc_i'),
        ),
        migrations.AddIndex(
            model_name='pagamento',
            index=models.Index(fields=['status', 'notificado_em'], name='core_pagamento_status_notif_i'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['pedido', '-enviada_em'], name='core_notificacao_ped_envia_i'),
        ),
    ]
